### ISSUE TITLE
Can slim-lint autocorrect problems?

### ISSUE THREAD

**Issue by AlexVPopov** [sds/slim-lint#16]
Is there a way for me to run slim-lint and have all hash-rocket syntax occurances be automatically turned into Ruby 1.9 hash syntax? I expect something like: `rubocop --only HashSyntax --auto-correct`. Thank you :smile:

**Comment by sds** [comment]
Hey @AlexVPopov,

Thanks for suggesting ways the tool could be improved. Unfortunately, this would be incredibly difficult to support, so you won't be seeing this implemented by me. 

The reason RuboCop supports auto-correction is because it uses the [`parser` gem](https://github.com/whitequark/parser) internally, which represents the parse tree in a way that allows it to be rewritten and serialized back into Ruby code. 

Unfortunately, the [Temple] framework used by Slim to parse documents does not keep track of all the additional metadata (source line numbers and offsets) of the parsed nodes&mdash;it wasn't designed to do that out of the box. Look at [this file](https://github.com/sds/slim-lint/blob/v0.6.0/lib/slim_lint/filters/inject_line_numbers.rb) to see what `slim-lint` does just to get line numbers out of the document.

Even if that challenge were conquered, the way `slim-lint` extracts Ruby code from a Slim document so RuboCop can actually run on it is currently a one-way process, so it would be difficult to port the transformations on the temporarily-generated Ruby file back to the original Slim document.

If someone is interested in implementing this, I would be open to a pull request, but I have a feeling it's a large enough endeavor to be its own project.

**Comment by AlexVPopov** [comment]
Hi @sds,

Thanks a lot for your very kind and thorough answer. :+1: 

Cheers,
Alex

**Comment by r7kamura** [comment]
In order to achieve auto-correction, I wrote yet another Slim parser called Slimi, that returns an AST with exact location information, and used it to create Slimcop. If you are interested, please give it a try.

- https://github.com/r7kamura/slimcop
- https://github.com/r7kamura/slimi
