### ISSUE TITLE
Law of demeter

### ISSUE THREAD

**Issue by timurvafin** [sds/slim-lint#19]
Not sure it could be implemented but it will be great to have a cop to catch things like this

```slim
= post.author.posts.count
```

Any thought?

**Comment by sds** [comment]
Hey @timurvafin, thanks for suggesting ways to improve the tool.

This kind of feature lies more in RuboCop's domain than Slim-Lint's, since it's purely a Ruby concern.

That aside, I think you'll have difficulty coming up with an automated way to detect this because there are legitimate situations where long chains of method calls are not violating the Law of Demeter. For example, when performing a series of transformations you'll likely have a series of `map`/`select`/`reject`/etc. calls chained together since you're operating on a list.

See https://github.com/bbatsov/rubocop/issues/720 for more discussion on this topic.
