### ISSUE TITLE
LineLength class

### ISSUE THREAD

**Issue by Kristinita** [sds/slim-lint#45]
I use [SublimeLinter-slim-lint](https://github.com/elstgav/SublimeLinter-slim-lint) plugin for Sublime Text. Example of my *Example.slim* file:

	| Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

In Status Bar I saw message:

	LineLength: Line is too long [448/80]

I have 2 questions:

1. Why do we need class [LineLength](http://www.rubydoc.info/github/sds/slim-lint/SlimLint/Linter/LineLength)? What is it good?
2. How can I disable this class?

I have tried:

	C:\WINDOWS\system32>slim-lint --show-linters
	Available linters:
 	+ CommentControlStatement
 	+ ConsecutiveControlStatements
 	+ EmptyControlStatement
 	+ LineLength
 	+ RedundantDiv
 	+ RuboCop
 	+ TagCase
 	+ TrailingWhitespace

	C:\WINDOWS\system32>slim-lint -x LineLength

	C:\WINDOWS\system32>slim-lint --show-linters
	Available linters:
 	+ CommentControlStatement
 	+ ConsecutiveControlStatements
 	+ EmptyControlStatement
 	+ LineLength
 	+ RedundantDiv
 	+ RuboCop
 	+ TagCase
 	+ TrailingWhitespace

The class is not disabled.

I read #12. Whether correctly I understood, what time can't disconnect separate linters at the moment?

Thanks.

**Comment by sds** [comment]
Hey @Kristinita,

To disable `LineLength` on every invocation of Slim-Lint, you need to create a `.slim-lint.yml` file in your repository root and add the following contents:

```yaml
linters:
  LineLength:
    enabled: false
```

Hope that helps!

**Comment by Kristinita** [comment]
@sds, thank you very much!

You could answer the first question?

> Why do we need class [LineLength](http://www.rubydoc.info/github/sds/slim-lint/SlimLint/Linter/LineLength)? What is it good?

**Comment by sds** [comment]
It depends on who you ask. 😄 

To me, enforcing a maximum line length has a few benefits:

* Code is [easier to read](http://www.humanfactors.com/newsletters/optimal_line_length.asp) since you minimize the amount of horizontal distance your eyes traverse
* You can fit the source code of multiple files horizontally on a screen, which is useful when using editors like [Vim](http://uw-freelancer.github.io/images/blog/insanely-faster-buffer-switching.png) or [Emacs](http://shenfeng.me/imgs/emacs-3-window.png) or [Sublime](http://lh3.ggpht.com/_1QSDkzYY2vc/TUQiv5Obq0I/AAAAAAAACy8/hccWEAZ14sQ/s2000/sublime-text-2_double-pane.png) to edit and view many files at once
* It helps point out areas of code that are complex or deeply-nested, as usually such blocks of code span many columns or are deeply-indented. By enforcing a maximum line length you are required to extract deeply-nested blocks into helpers so that they don't take up as much space (or otherwise simplify them).

There are other benefits, but these are the ones that immediately come to mind. Hope that helps!
